### ISSUE TITLE
SQLDataException: (conn:1989635) Data too long for column 'name' at row 1

### ISSUE THREAD

**Issue by mibby** [ruany/LiteBans#21]
Litebans v2.2.4

Trying to import my vanilla banned players and banned IPs json file into the litebans mariaDB (mysql) database.
```/litebans import start```

```
[05:44:05] [pool-8-thread-4/ERROR]: [LiteBans] An unexpected database error has occurred.
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] java.sql.SQLDataException: (conn:1989635) Data too long for column 'name' at row 1
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:245)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:153)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:186)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at litebans.aq.executeUpdate(aq.java:5)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at litebans.aF.executeUpdate(aF.java)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at litebans.ax.b(ax.java:1)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at litebans.cQ.b(cQ.java:32)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at litebans.bu.b(bu.java:235)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at litebans.d2.run(d2.java:301)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] Caused by: java.sql.SQLException: Data too long for column 'name' at row 1
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] Query is: INSERT INTO litebans_history (name,uuid,ip) VALUES (?,?,?), parameters ['The_Elder__MageGreif','94f9e279-869e-3c83-ac28-6bebb83f4bae','#undefined#']
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:223)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:212)
[05:44:05] [pool-8-thread-4/WARN]: [LiteBans] 	... 12 more
```

```
# After configuring import options, run "/litebans import start" to begin the import.
# The import process occurs while the server is running, no downtime is required.
import:
  # You can import from: MaxBans, Ultrabans, BanHammer, BanManagerv4, BanManagerv5, BungeeAdminTools, LiteBans, Vanilla.
  # Vanilla means importing from banned-players.json, which is also used by Essentials.
  from: Vanilla

  # If enabled, importing will be done from a SQLite database instead of a MySQL database.
  # You can ignore this if importing from banned-players.json.
  # If importing from LiteBans, H2 will be used instead of SQLite.
  sqlite: true

  # SQLite file locations:
  #  MaxBans: plugins/MaxBans/bans.db
  #  Ultrabans: plugins/Ultrabans/banlist.db
  #  BanHammer: plugins/BanHammer/BanHammer.db
  #  LiteBans: plugins/LiteBans/litebans.sqlite (legacy)
  sqlite_file: plugins/MaxBans/bans.db

  import_ipbans: true
  ## MySQL import settings ##
  import_mysql_address: localhost:3306
  import_mysql_database: maxbans
  import_mysql_username: ''
  import_mysql_password: ''
```

After a little bit of time, this was outputted to my client.

```
[05:44:12] [main/INFO]: [CHAT] Fixing history for table litebans_bans...
[05:44:13] [main/INFO]: [CHAT] Added 0 entries.
[05:44:13] [main/INFO]: [CHAT] 27 UUIDs were not fetched from Mojang since they are offline-mode UUIDs.
[05:44:13] [main/INFO]: [CHAT] Fixing history for table litebans_mutes...
[05:44:13] [main/INFO]: [CHAT] Added 0 entries.
[05:44:13] [main/INFO]: [CHAT] 27 UUIDs were not fetched from Mojang since they are offline-mode UUIDs.
[05:44:13] [main/INFO]: [CHAT] Fixing history for table litebans_warnings...
[05:44:13] [main/INFO]: [CHAT] Added 0 entries.
[05:44:13] [main/INFO]: [CHAT] 27 UUIDs were not fetched from Mojang since they are offline-mode UUIDs.
[05:44:13] [main/INFO]: [CHAT] Fixing history for table litebans_kicks...
[05:44:13] [main/INFO]: [CHAT] Added 0 entries.
[05:44:13] [main/INFO]: [CHAT] 27 UUIDs were not fetched from Mojang since they are offline-mode UUIDs.
[05:44:13] [main/INFO]: [CHAT] Import finished successfully. 1981 bans imported, 0 IP-bans.
```

**Comment by mibby** [comment]
Is there any way to import the banned-ips.json into the database? As it didn't seem to do so according to the 0 IP-bans output.

Also is there any way to ensure the 27 non-UUID players are still imported and kept banned? As they most certainly should not be allowed back on the server.

**Comment by ruany** [comment]
All of the UUID bans were imported successfully into the database and will take effect, but the bans may not appear in /history, /staffhistory, /banlist, or on the web interface.

The plugin failed to add one of your banned players to the history table because he has an invalid name longer than 16 characters, but his ban will still take effect. The error can be safely ignored.

Banned-ips.json isn't supported at the moment, but that's a separate issue.

**Comment by mibby** [comment]
Alright, thanks for the quick reply! Just bought the plugin and migrating over from Essentials/vanilla. 

Does LiteBans supersede the ban json files so if a player is unbanned later, the file itself is ignored if they are still banned there?

**Comment by ruany** [comment]
You'll have to delete banned-players.json after importing, otherwise vanilla will still apply the bans.

**Comment by mibby** [comment]
Oh, good to know. I will go ahead and do that now then and keep the IP bans until that importing is supported.
