### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by CryLegende** [ruany/LiteBans#47]
`[16:24:53] [Thread-220/WARN]: [LiteBans] AsyncPlayerPreLoginEvent.getAddress() == null (GaB41150)
[16:24:53] [Thread-220/INFO]: UUID of player GaB41150 is e8176c8e-6edb-33b3-a68c-8ebd6c20ba80
[16:24:53] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to LiteBans v2.2.9
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:472) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:118) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at litebans.aU.a(aU.java:52) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor502.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[SkyBlock.jar:git-PaperSpigot-"4c7641d"]
	... 14 more
[16:24:53] [Server thread/INFO]: [+] GaB41150`
or
https://hastebin.com/ijigibabof.vbs
(This happens when a player connects to the server, it is asser rare but its cause lags and the player can not be punished.)

**Comment by ruany** [comment]
The error has already been fixed in 2.2.13 (silent update) which was released a few weeks ago.

It wasn't released as a major update because it's not normal to have players without IP addresses and this breaks several parts of the plugin (dupeip, alt detection, IP bans, IP history, GeoIP) thus the warning on login.
